name: build-deploy

on:
  push:
    branches: [ master ]

env:
  PROJECT_NAME: hello3
  TIER: ${{
    ( github.ref == 'refs/heads/develop' && 'dev')
    || ( github.ref == 'refs/heads/qa' && 'qa')
    || ( github.ref == 'refs/heads/stage' && 'stage')
    || ( github.ref == 'refs/heads/master' && 'green')
    || 'unspecified'
    }}
  CLUSTER_PROJECT_NAME: hello-cluster
  CLUSTER_PROJECT_ORG: alex-egorov
  CLUSTER_BRANCH: 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      
    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: |
        CGO_ENABLED=0 go test ./...
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_IMAGE: ${{ env.PROJECT_NAME }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE }}
        tags: ${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check out the cluster repo
      uses: actions/checkout@v2.3.0
      with:
        repository: ${{ env.CLUSTER_PROJECT_ORG }}/${{ env.CLUSTER_PROJECT_NAME }}
        token: ${{ secrets.ACCESS_TOKEN }}
        path: ${{ env.CLUSTER_PROJECT_NAME }}
        ref: ${{ env.CLUSTER_BRANCH }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.10.0"

    - name: Update kubernetes version
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_IMAGE: ${{ env.PROJECT_NAME }}
      run: |
        #!/bin/sh -e
        pushd ${CLUSTER_PROJECT_NAME}/cluster/manifests/${PROJECT_NAME}/${TIER}/
          kustomize edit set image ${DOCKER_IMAGE}=${DOCKER_REPO}/${DOCKER_IMAGE}:${GITHUB_SHA}
        popd

    - name: Push changes to repo
      run: |
        #!/bin/sh -e
        pushd ${CLUSTER_PROJECT_NAME}/cluster/manifests/${PROJECT_NAME}/${TIER}/
        MESSAGE="
          Pushing version update for deployment
          Repo: ${{ github.repository }}
          Revision: ${{ github.sha }}
          Workflow: ${{ github.workflow }}
          Event: ${{ github.event_name }}
          Application Branch: ${{ github.ref }}
          Cluster Branch: ${CLUSTER_BRANCH}
          Image: ${IMAGE}
          Actions Url: ${{ format('{0}/actions/runs/{1}', github.event.repository.html_url, github.run_id) }}
        "
        if ! git diff-index --quiet HEAD; then
          git config --global user.name "${{ github.repository }}"
          git config --global user.email "<action@github.com>"
          git commit --allow-empty -m "${MESSAGE}" kustomization.yaml
          git push origin ${CLUSTER_BRANCH}
        fi
        popd

